In [1]:
import numpy as np
import pandas as pd

Considere os arrays numpy X, y abaixo:

In [2]:
from sklearn.datasets import load_iris

X = load_iris().data
y = load_iris().target

In [3]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

__Exercício 1:__ Crie um dataframe df do pandas a partir de X, y.

Primeiro, concatene os arrays numpy. Na sequência transforme o array final para um dataframe. Altere o nome das colunas para 'X1', 'X2', 'X3', 'X4' e 'target'.

In [5]:
df_X = pd.DataFrame(X, columns=["X1","X2","X3","X4"])
df_y = pd.DataFrame(y, columns=["target"])

In [6]:
df = pd.concat([df_X,df_y], axis=1)

__Exercício 2:__ Usando o df criado no exercício 1, calcule qual a média da variável 'X2', para cada valor de target. Dica: Use a função groupby no dataframe df para resolver.

In [7]:
df_X2_mean = df.groupby('target').agg({"X2":'mean'})

In [8]:
print(df_X2_mean)

           X2
target       
0       3.428
1       2.770
2       2.974


__Exercício 3:__ Construa um dicionário mapeando os valores:
        
        0 - 'A'
        
        1 - 'B'
        
        2 - 'C'
        
Usando a função map, crie uma coluna nova no dataframe df chamada 'target_2' com o mapeamento feito. Dica: Use a função map como visto em aula.

In [9]:
df["target_2"] = df.target.map({0:'A',1:'B',2:'C'})
df["target_2"].unique()

array(['A', 'B', 'C'], dtype=object)

In [10]:
print(df.head(5))

    X1   X2   X3   X4  target target_2
0  5.1  3.5  1.4  0.2       0        A
1  4.9  3.0  1.4  0.2       0        A
2  4.7  3.2  1.3  0.2       0        A
3  4.6  3.1  1.5  0.2       0        A
4  5.0  3.6  1.4  0.2       0        A


__Exercício 4:__ 


4.1: Filtre o dataframe df onde X1 é maior do que 6 __ou__ target é diferente de 2 e chame-o de df1. Dica: usar os filtros e os operadores vistos em aula;

4.2: Filtre os primeiros 15 índices do dataframe df e chame-o de df2;

4.3: Transformando os dataframes df1 e df2 para arrays. Multiplique df1 pelo transposto de df2 (use a função que calcula transposta de matriz) e printe o resultado final. Lembre-se de dropar a coluna target_2 de cada um dos dataframes antes de fazer a mutliplicação.

In [11]:
df1 = df[(df.X1 > 6) | (df.target != 2)]
print(df1.head(5))

    X1   X2   X3   X4  target target_2
0  5.1  3.5  1.4  0.2       0        A
1  4.9  3.0  1.4  0.2       0        A
2  4.7  3.2  1.3  0.2       0        A
3  4.6  3.1  1.5  0.2       0        A
4  5.0  3.6  1.4  0.2       0        A


In [12]:
df2 = df[:15]
print(df2)

     X1   X2   X3   X4  target target_2
0   5.1  3.5  1.4  0.2       0        A
1   4.9  3.0  1.4  0.2       0        A
2   4.7  3.2  1.3  0.2       0        A
3   4.6  3.1  1.5  0.2       0        A
4   5.0  3.6  1.4  0.2       0        A
5   5.4  3.9  1.7  0.4       0        A
6   4.6  3.4  1.4  0.3       0        A
7   5.0  3.4  1.5  0.2       0        A
8   4.4  2.9  1.4  0.2       0        A
9   4.9  3.1  1.5  0.1       0        A
10  5.4  3.7  1.5  0.2       0        A
11  4.8  3.4  1.6  0.2       0        A
12  4.8  3.0  1.4  0.1       0        A
13  4.3  3.0  1.1  0.1       0        A
14  5.8  4.0  1.2  0.2       0        A


In [13]:
df1 = df1.drop("target_2", axis = 1).to_numpy()
df2 = df2.drop("target_2", axis = 1).to_numpy()
print(np.dot(df1,df2.T))

[[40.26 37.49 37.03 ... 36.96 33.99 45.3 ]
 [37.49 35.01 34.49 ... 34.5  31.63 42.14]
 [37.03 34.49 34.06 ... 34.   31.26 41.66]
 ...
 [48.26 45.75 44.49 ... 44.93 40.28 52.92]
 [51.33 48.53 47.31 ... 47.68 42.87 56.34]
 [51.54 48.6  47.5  ... 47.75 43.03 56.5 ]]


__Exercício 5:__ 
    
5.1: Crie uma função que receba um  número inteiro positivo N e retorne um array 0, 1, ..., N. Dica: Use as funções que vimos para criação de arrays;
    
5.2: Crie uma função que receba um array [0,1, .., N] e retorne o mesmo array, só que com os números em posições aleatórias. Dica: use a função que vimos em aula que faz escolhas aleatórias SEM reposição;

5.3: Crie uma função que receba um número inteiro positivo N. Essa função deve retornar um array de tamanho N, cujos valores são números inteiros entre 0 e N-1 e pode haver repetição desses números.

In [14]:
def numero(n):
    arr_num = np.arange(n)
    return arr_num
numero(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
def numero(n):
    arr_num = np.arange(n)
    arr_num = np.random.choice(arr_num,size = n, replace=False)
    return arr_num
numero(10)

array([7, 6, 4, 8, 3, 5, 1, 2, 9, 0])

In [16]:
def numero(n):
    arr_num = np.random.randint(0,n,size=n)
    return arr_num
numero(12)

array([ 6,  8, 10,  9,  0,  4,  8,  1,  0,  1,  8,  9])

__Exercício 6:__ Construa uma função divide_dados:
        
        - recebe um array X de dimensões quaisquer (n,k) e um parâmetro p entre 0 e 1.
        - divide o array X em duas partes disjuntas de forma aleatória. Ou seja, crie dois novos arrays, X1 e X2,
        onde a dimensão de linhas de X1 somada com a dimensão de linhas de X2 deve ser igual a dimensão de linhas de X.
        - interpretando p como percentual, o tamanho de X1 deve ser p*100% do número de linhas de X; enquanto X2 deve ser o resto.
        - retorne esses dois arrays.
        
       

In [17]:
def divide_dados(array, p):
    cp_array = array
    np.random.shuffle(cp_array)
    maximo = int(len(array)*p)
    X1 = array[:maximo]
    X2 = array[maximo:]
    return X1, X2

In [18]:
bid_array = np.array([[1,2,3,0,5],[4,5,6,1,2]])

In [19]:
X1, X2 = divide_dados(bid_array, 0.75)

In [20]:
print(X1)

[[1 2 3 0 5]]


In [21]:
print(X2)

[[4 5 6 1 2]]
